/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ca8b7f47636d0166bc76489d064897e)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
