/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4cfa1ffbb0f12c6d5474760e59d35213)
interface __BaseEnv_Env {
	IMAGES: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET">> {}
}
