/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelebritiesRouteImport } from './routes/celebrities'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as RankingQuizIdRouteImport } from './routes/ranking.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebritiesRoute = CelebritiesRouteImport.update({
  id: '/celebrities',
  path: '/celebrities',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingQuizIdRoute = RankingQuizIdRouteImport.update({
  id: '/ranking/$quizId',
  path: '/ranking/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebrities': typeof CelebritiesRoute
  '/images/$': typeof ImagesSplatRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/ranking/$quizId': typeof RankingQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebrities': typeof CelebritiesRoute
  '/images/$': typeof ImagesSplatRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/ranking/$quizId': typeof RankingQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebrities': typeof CelebritiesRoute
  '/images/$': typeof ImagesSplatRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/ranking/$quizId': typeof RankingQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/celebrities' | '/images/$' | '/quiz/$quizId' | '/ranking/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celebrities' | '/images/$' | '/quiz/$quizId' | '/ranking/$quizId'
  id:
    | '__root__'
    | '/'
    | '/celebrities'
    | '/images/$'
    | '/quiz/$quizId'
    | '/ranking/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebritiesRoute: typeof CelebritiesRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  RankingQuizIdRoute: typeof RankingQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrities': {
      id: '/celebrities'
      path: '/celebrities'
      fullPath: '/celebrities'
      preLoaderRoute: typeof CelebritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/$quizId': {
      id: '/ranking/$quizId'
      path: '/ranking/$quizId'
      fullPath: '/ranking/$quizId'
      preLoaderRoute: typeof RankingQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebritiesRoute: CelebritiesRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  RankingQuizIdRoute: RankingQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
